# Generated by Django 5.0.6 on 2024-11-01 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='common',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='last_publish',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='author',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book_store.common')),
                ('address', models.CharField(max_length=100)),
            ],
            bases=('book_store.common',),
        ),
        migrations.CreateModel(
            name='reader',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book_store.common')),
                ('likes', models.CharField(max_length=30)),
                ('dislikes', models.CharField(max_length=30)),
            ],
            bases=('book_store.common',),
        ),
    ]
