# Generated by Django 5.0.6 on 2024-11-01 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0002_common_alter_bookmodel_last_publish_author_reader'),
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='man',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book_store.people')),
                ('power', models.BooleanField()),
                ('monogamy', models.BooleanField()),
            ],
            bases=('book_store.people',),
        ),
        migrations.CreateModel(
            name='women',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book_store.people')),
                ('married', models.BooleanField()),
                ('unmarried', models.BooleanField()),
            ],
            bases=('book_store.people',),
        ),
    ]
