# Generated by Django 5.0.6 on 2024-11-01 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0003_people_man_women'),
    ]

    operations = [
        migrations.CreateModel(
            name='friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=30)),
                ('attendance', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='me',
            fields=[
                ('friend_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book_store.friend')),
            ],
            bases=('book_store.friend',),
        ),
    ]
